sonar.organization=guibranco
sonar.projectKey=guibranco_finorganizer-ui
sonar.projectName=finorganizer-ui

# Path to sources and tests
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.ts,tests/**/*.test.tsx

# Source encoding
sonar.sourceEncoding=UTF-8

# Coverage report path
sonar.javascript.lcov.reportPaths=coverage/lcov.info
